# Generated by Django 5.0.7 on 2026-08-23 04:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=120)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Client Inquiry',
                'verbose_name_plural': 'Client Inquiries',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('role_category', models.CharField(choices=[('founder', 'Founder'), ('cofounder', 'Co-Founder'), ('team', 'Team Member')], max_length=20)),
                ('job_title', models.CharField(help_text="e.g. 'Founder & Data Analyst', 'Power BI Developer'", max_length=120)),
                ('bio', models.TextField(help_text='Short 2-4 sentence bio shown on the site.')),
                ('photo', models.ImageField(help_text='Square photo recommended (min 500x500px).', upload_to='team_photos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('linkedin_url', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first within their section.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this person from the live site without deleting them.')),
                ('date_joined', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['role_category', 'display_order', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('client_name', models.CharField(blank=True, help_text='Optional - leave blank if confidential.', max_length=120)),
                ('summary', models.TextField(help_text='What the project was about and the outcome.')),
                ('tools_used', models.CharField(help_text="Comma-separated, e.g. 'Python, Pandas, Power BI'", max_length=200)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='project_covers/')),
                ('project_url', models.URLField(blank=True, help_text='Link to GitHub repo, dashboard, or live demo.')),
                ('status', models.CharField(choices=[('draft', 'Draft (hidden from site)'), ('published', 'Published (visible on site)')], default='published', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_added', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
